test access

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -77,38 +77,55 @@ jobs:
           export bastion_session_ocid=`cat ~/bastion_session.json | grep bastionsession | awk '{print $2}' | tail -1 | tr -d '"'`          
           echo "bastion_session_ocid=$bastion_session_ocid" >> "$GITHUB_ENV"
 
-      # - name: Get GitHub Runner Public IP
-      #   run: |
-      #     IP=$(curl -s https://api.ipify.org)
-      #     echo "RUNNER_IP=$IP" >> $GITHUB_ENV
-      #     echo "Runner IP: $IP"
+      - name: Get GitHub Runner Public IP
+        run: |
+          IP=$(curl -s https://api.ipify.org)
+          echo "RUNNER_IP=$IP" >> $GITHUB_ENV
+          echo "Runner IP: $IP"
 
-      # - name: Add Runner IP to Bastion Allowlist
-      #   run: |
-      #     NEW_IP="${RUNNER_IP}/32"
+      - name: Add Runner IP to Bastion Allowlist
+        run: |
+          NEW_IP="${RUNNER_IP}/32"
 
-      #     # Get existing allowlist as JSON array
-      #     CURRENT=$(oci bastion bastion get \
-      #       --bastion-id ${{ secrets.BASTION_OCID }} \
-      #       --query 'data."client-cidr-block-allow-list"' \
-      #       --raw-output)
+          # Get existing allowlist as JSON array
+          CURRENT=$(oci bastion bastion get \
+            --bastion-id ${{ secrets.BASTION_OCID }} \
+            --query 'data."client-cidr-block-allow-list"' \
+            --raw-output)
 
-      #     echo "Current allowlist: $CURRENT"
+          echo "Current allowlist: $CURRENT"
 
-      #     # Use jq to append only if not already present
-      #     UPDATED=$(echo "$CURRENT" | jq --arg ip "$NEW_IP" '
-      #       if index($ip) then . else . + [$ip] end
-      #     ')
+          # Use jq to append only if not already present
+          UPDATED=$(echo "$CURRENT" | jq --arg ip "$NEW_IP" '
+            if index($ip) then . else . + [$ip] end
+          ')
 
-      #     echo "Updated allowlist: $UPDATED"
+          echo "Updated allowlist: $UPDATED"
 
-      #     oci bastion bastion update --bastion-id ${{ secrets.BASTION_OCID }} --client-cidr-list "$UPDATED" --force
+          oci bastion bastion update --bastion-id ${{ secrets.BASTION_OCID }} --client-cidr-list "$UPDATED" --force
 
       - name: Install kubectl
         run: |
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
           sudo chmod 755 kubectl
           sudo mv kubectl /usr/local/bin
+      
+      - name: Configure OKE Cluster
+        run: |
+          oci ce cluster create-kubeconfig --cluster-id ${{ vars.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT          
+          sed -i "s|${{ env.oke_private_ip }}|127.0.0.1|g" $HOME/.kube/config
+          sleep 5
+          kubectl cluster-info
+          if [ $? == 0 ]
+          then
+            echo "---------------------------------------------------------------"
+            echo "Successfully Connected to your Private OKE Cluster"
+            echo "---------------------------------------------------------------"
+          else
+            echo "---------------------------------------------------------------"
+            echo "Unable to Authenticate with Private OKE Cluster"
+            echo "---------------------------------------------------------------"
+          fi
 
       - name: Start SSH Tunnel to OKE Cluster
         # run: |          
@@ -127,30 +144,13 @@ jobs:
           -o ServerAliveInterval=30 \
           -o ServerAliveCountMax=3 \
           -o StrictHostKeyChecking=no \
-          -N -L 6443:${oke_private_ip}:6443 \
+          -N -L 6443:${oke_private_ip}:6443 -p 22 \
           ${bastion_session_ocid}@${{ secrets.BASTION_HOST }} > ssh_tunnel.log 2>&1 &
 
       # - name: Noti
       #   run: |
       #     sleep 5
       #     nc -zv 127.0.0.1 6443
-
-      - name: Configure OKE Cluster
-        run: |
-          oci ce cluster create-kubeconfig --cluster-id ${{ vars.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT          
-          sed -i "s|${{ env.oke_private_ip }}|127.0.0.1|g" $HOME/.kube/config
-          sleep 5
-          kubectl cluster-info
-          if [ $? == 0 ]
-          then
-            echo "---------------------------------------------------------------"
-            echo "Successfully Connected to your Private OKE Cluster"
-            echo "---------------------------------------------------------------"
-          else
-            echo "---------------------------------------------------------------"
-            echo "Unable to Authenticate with Private OKE Cluster"
-            echo "---------------------------------------------------------------"
-          fi
 
       - name: Deploy to OKE
         run: |
